const express = require('express')
const router = express.Router()
const adminController = require('../controller/adminController')
const auth = require('../middlewares/auth')
const upload = require('../middlewares/upload')

router.get('/login', auth.isLoginAdmin, adminController.loadLogin)
router.post('/login', adminController.loginAdmin)
router.get('/dashboard', auth.checkSessionAdmin, adminController.loadDashboard)
router.get('/blockUser/:id', adminController.blockUser)
router.get('/unblockUser/:id', adminController.unblockUser)
router.get('/products', auth.checkSessionAdmin, adminController.loadProducts)
router.get('/addProducts', auth.checkSessionAdmin, adminController.loadAddProducts)
router.post('/addProducts', upload.upload, adminController.addProduct);
router.get('/unlistProduct/:id', adminController.unlistProduct)
router.get('/listProduct/:id', adminController.listProduct)
router.get('/editProduct/:id', adminController.loadEditProduct)
router.post('/editProduct/:id', upload.upload, adminController.editProduct)
router.get('/logout', auth.isLogin, adminController.logoutAdmin)
router.get('/category', adminController.loadCategory)
router.get('/addCategory', adminController.loadAddCategory)
router.post('/addCategory', upload.uploadSingle, adminController.addCategory)
router.get('/addProductToCategory/:id', adminController.loadCategoryManagement)
router.get('/postProductToCategory', adminController.postProductToCategory)
router.get('/deleteCategory/:id', adminController.deleteCategory)
module.exports = router;